usr/bin/kcron
usr/share/applications/kde4/kcron.desktop
usr/share/kde4/apps/kcron/kcronui.rc
usr/share/icons/hicolor/22x22/apps/kcron.png
usr/share/icons/hicolor/16x16/apps/kcron.png
usr/share/icons/hicolor/32x32/apps/kcron.png
usr/share/doc/kde4/HTML/en/kcron/index.cache.bz2
usr/share/doc/kde4/HTML/en/kcron/index.docbook
usr/share/doc/kde4/HTML/en/kcron/newvariable.png
usr/share/doc/kde4/HTML/en/kcron/kcronstart.png
usr/share/doc/kde4/HTML/en/kcron/newtask.png
usr/share/doc/kde4/HTML/en/kcron/kcron.png
usr/share/doc/kde4/HTML/en/kcron/print.png

debian/icons/kcron.xpm      /usr/share/pixmaps
debian/icons/kcron-16.xpm   /usr/share/pixmaps
