debian/debug.py usr/share/kde4/apps/system-config-printer-kde/
debian/ppdippstr.py usr/share/kde4/apps/system-config-printer-kde/
debian/pysmb.py usr/share/kde4/apps/system-config-printer-kde/
debian/smburi.py usr/share/kde4/apps/system-config-printer-kde/
usr/share/kde4/apps/system-config-printer-kde/authconn.py
usr/share/kde4/apps/system-config-printer-kde/ipp-browse-dialog.ui
usr/share/kde4/apps/system-config-printer-kde/new-printer.ui
usr/share/kde4/apps/system-config-printer-kde/options.py
usr/share/kde4/apps/system-config-printer-kde/optionwidgets.py
usr/share/kde4/apps/system-config-printer-kde/pysmb.py
usr/share/kde4/apps/system-config-printer-kde/smb-browse-dialog.ui
usr/share/kde4/apps/system-config-printer-kde/system-config-printer-kde.py
usr/share/kde4/apps/system-config-printer-kde/system-config-printer.ui
usr/share/kde4/services/system-config-printer-kde.desktop
