usr/share/kde4/apps/system-config-printer-kde/ipp-browse-dialog.ui
usr/share/kde4/apps/system-config-printer-kde/new-printer.ui
usr/share/kde4/apps/system-config-printer-kde/options.py
usr/share/kde4/apps/system-config-printer-kde/optionwidgets.py
usr/share/kde4/apps/system-config-printer-kde/smb-browse-dialog.ui
usr/share/kde4/apps/system-config-printer-kde/system-config-printer-kde.py
usr/share/kde4/apps/system-config-printer-kde/system-config-printer.ui
usr/share/kde4/services/system-config-printer-kde.desktop
